services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
      POSTGRES_DB: finance
    volumes:
      - finance-postgres-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro

volumes:
  finance-postgres-data:
